spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///library?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.hzhang.pojo
server:
  port: 8002
pagehelper:
  auto-dialect: mysql
  reasonable: true
  support-methods-arguments: true
#logging:
#  level:
#    com:
#      hzhang:
#        dao: debug
